### ISSUE TITLE
Spaces in filename, or expand to boundary

### ISSUE THREAD

**Issue by xHN35RQ** [stevenhauser/open-sesame#9]
Is there a way to support filenames with spaces in them? Given a filename of `File Name With Spaces.pdf` then open-sesame will try to use just one of the words. (File, Name, With, or Spaces.pdf)

I can see that determining what is part of the filename would be difficult given we can't rely on spaces as delimiters. Perhaps by expanding to brackets or quotes? Maybe a settings option to set a boundary mark of single or double quotes, or types of brackets... or maybe even expanding to full lines? Or perhaps more simply, allow users to set custom regex in the settings panel.

What do you suggest is a good way to handle this? I'm willing to take a stab at a solution and give a PR although I don't know much Coffescript atm.

Thanks for this very helpful plugin!

**Comment by stevenhauser** [comment]
Man, I suck—I never got a notification for this and am just now seeing it, sorry. I think some sort of configuration setting is probably the way to go.

**Comment by xHN35RQ** [comment]
No worries. :smile: That would be super helpful to have.

**Comment by stevenhauser** [comment]
Customizing the regex seems ok, but perhaps kind of advanced for some people. I wonder if it makes sense to default to how it works now, but support opening files under the *selection*. So if you had to open a more "complex" filename, you'd select the text of it. Would that work for you?

**Comment by xHN35RQ** [comment]
Sure, I guess I can figure out a way to expand selection automatically to brackets. I'm mostly looking to put `[]` brackets around filenames as a way of allowing quick access from a Markdown document to local supporting documents in the same folder, or sub-folders.

**Comment by stevenhauser** [comment]
Oh yeah I'm pretty sure Atom supports that out of the box. If not, there's
a Bracket Matcher plugin, or—one of my personal favorite plugins—
https://atom.io/packages/expand-region.

**Comment by xHN35RQ** [comment]
Thank I'll look into it!!

**Comment by stevenhauser** [comment]
Cool. And I can look into opening under a selection within the next few
days or week. Unless you're wanting to contribute that code? Either way
works for me.

**Comment by xHN35RQ** [comment]
I'm still a coffescript noob. I'll try to work on it but I can promise nothing. :wink: But I'd like to get to the place soon where this would have been a Pull Request instead of an issue.

**Comment by stevenhauser** [comment]
Ok cool, I'll hold off on working on it on my end for a bit then.
Definitely feel free to submit something and ask questions on any
CoffeeScript stuff. I'm not really a huge fan but it was the desired
language to write packages in when I wrote this one and I haven't felt like
changing it over to ES2015. Thankfully Atom is switching to ES2015 now.

**Comment by xHN35RQ** [comment]
Sounds good. Thanks!

**Comment by xHN35RQ** [comment]
@stevenhauser So this seems to be working nicely for me to open files under current selection. But it's my first time writing Coffeescript, please have a look to see if I've done anything incorrectly. Thanks!

**Comment by stevenhauser** [comment]
@xHN35RQ thanks for looking into that! Can you create a PR into this repo with your changes? That'll make it easier for me to try out your changes and merge them in.

And yeah, I'd like to convert all my old Coffeescript to ES2015 at some point. Back in olden times we didn't have it and I didn't realize you could write ES5 for Atom plugins—thought they had to be CS!

**Comment by xHN35RQ** [comment]
Done! Thanks. https://github.com/stevenhauser/open-sesame/pull/10
